version: "3.9"

services:
  db:
    image: mysql:8.0.27
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB_NAME}
    ports:
      - "3337:3306"
volumes:
  dbdata:
