INSERT INTO PUBLIC.TASK (ID, NAME)
VALUES (7, 'Home Office');
INSERT INTO PUBLIC.TASK (ID, NAME)
VALUES (8, 'Office Time');
INSERT INTO PUBLIC.TASK (ID, NAME)
VALUES (9, 'Vacation');

INSERT INTO PUBLIC.USER (ID, FIRSTNAME, LASTNAME, LOGIN, PASSWORD_HASH, ROLE)
VALUES (3, 'Lukas', 'Fink', 'lukas', '$2a$10$KFXlSOeUfQXr0s.bffZ/n.5KZ0QHdMwTGx/zE8jiWDQNH6.tXXBlC', 'ADMIN');
INSERT INTO PUBLIC.USER (ID, FIRSTNAME, LASTNAME, LOGIN, PASSWORD_HASH, ROLE)
VALUES (5, 'Schahnaz Isabel', 'Westenberger', 'izzy', '$2a$10$D9EM2f/PDviL..x0tI2Tq.uY5KBM78mn6YA22P2/sR8.yoaRohbgq',
        'ADMIN');
INSERT INTO PUBLIC.USER (ID, FIRSTNAME, LASTNAME, LOGIN, PASSWORD_HASH, ROLE)
VALUES (6, 'David Gerhard', 'Hahn', 'elayoe', '$2a$10$CKhruEef4dfrvEjxGD4L2.ajFGPblCOysysa0qodM/N0JEiS/5F6W', 'ADMIN');

